addons:
  apt:
    packages:
      - docker-ce

sudo: required
language: python

services:
  - docker

install:
  - pip install tox

env:
  - TOX_ENV: py27-ansible25
  - TOX_ENV: py27-ansible26
  - TOX_ENV: py27-ansible27

script:
  - tox -e ${TOX_ENV}
