services:
  - docker

env:
  - distribution: centos
    version: 7
    ansible_version: 2.6.3
  - distribution: debian
    version: stretch
    ansible_version: 2.6.3
  - distribution: ubuntu
    version: xenial
    ansible_version: 2.6.3

script:
  - ./tests/test.sh
