- name: Install https method
  apt:
    name: apt-transport-https

- name: Add APT key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Configure repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release }} stable"
    update_cache: true

- name: Install docker and dependencies
  apt:
    name:
      - "{{ docker_pkg }}{% if docker_version %}={{ docker_version }}{% endif %}"
      - virtualenv
      - python-setuptools
