- name: Configure logins
  docker_login:
    api_version: "{{ item.api_version | default(omit) }}"
    cacert_path: "{{ item.cacert_path | default(omit) }}"
    cert_path: "{{ item.cert_path | default(omit) }}"
    config_path: "{{ item.config_path | default(omit) }}"
    debug: "{{ item.debug | default(omit) }}"
    docker_host: "{{ item.docker_host | default(omit) }}"
    email: "{{ item.email | default(omit) }}"
    key_path: "{{ item.key_path | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    reauthorize: "{{ item.reauthorize | default(omit) }}"
    registry_url: "{{ item.registry_url | default(omit) }}"
    ssl_version: "{{ item.ssl_version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    tls: "{{ item.tls | default(omit) }}"
    tls_hostname: "{{ item.tls_hostname | default(omit) }}"
    tls_verify: "{{ item.tls_verify | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
  loop: "{{ docker_logins }}"
  vars:
    ansible_python_interpreter: "{{ docker_virtualenv_path }}/bin/python"
