- name: Configure docker services
  docker_service:
    api_version: "{{ item.api_version | default(omit) }}"
    build: "{{ item.build | default(omit) }}"
    cacert_path: "{{ item.cacert_path | default(omit) }}"
    cert_path: "{{ item.cert_path | default(omit) }}"
    debug: "{{ item.debug | default(omit) }}"
    definition: "{{ item.definition | default(omit) }}"
    dependencies: "{{ item.dependencies | default(omit) }}"
    docker_host: "{{ item.docker_host | default(omit) }}"
    files: "{{ item.files | default(omit) }}"
    hostname_check: "{{ item.hostname_check | default(omit) }}"
    key_path: "{{ item.key_path | default(omit) }}"
    nocache: "{{ item.nocache | default(omit) }}"
    project_name: "{{ item.project_name | default(omit) }}"
    project_src: "{{ item.project_src | default(omit) }}"
    pull: "{{ item.pull | default(omit) }}"
    recreate: "{{ item.recreate | default(omit) }}"
    remove_images: "{{ item.remove_images | default(omit) }}"
    remove_orphans: "{{ item.remove_orphans | default(omit) }}"
    remove_volumes: "{{ item.remove_volumes | default(omit) }}"
    restarted: "{{ item.restarted | default(omit) }}"
    scale: "{{ item.scale | default(omit) }}"
    services: "{{ item.services | default(omit) }}"
    ssl_version: "{{ item.ssl_version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    stopped: "{{ item.stopped | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    tls: "{{ item.tls | default(omit) }}"
    tls_hostname: "{{ item.tls_hostname | default(omit) }}"
    tls_verify: "{{ item.tls_verify | default(omit) }}"
  loop: "{{ docker_services }}"
  vars:
    ansible_python_interpreter: "{{ docker_virtualenv_path }}/bin/python"
